//PRODUCTS
export const ADDPRODUCT = 'ADDPRODUCT';
export const UPDATEPRODUCT = 'UPDATEPRODUCT';
export const DELETEPRODUCT = 'DELETEPRODUCT';
export const FETCHPRODUCTS = 'FETCHPRODUCTS';

//ORDERS
export const CREATEORDER="CREATEORDER";
export const GETUSERORDERS="GETUSERORDERS";

//Auth
export const LOGOUT="LOGOUT"
export const AUTH="AUTH"


